"""DHF change impact analyzer (DHF-015).

Given a list of changed file paths, classifies which DHF sections need
updating — auto (regenerated by generate_dhf.py) or manual (human review).
"""
from __future__ import annotations

import fnmatch
from dataclasses import dataclass, field


@dataclass
class ImpactSection:
    dhf_file: str
    reason: str
    label: str


@dataclass
class ImpactReport:
    auto_sections: list[ImpactSection] = field(default_factory=list)
    manual_sections: list[ImpactSection] = field(default_factory=list)

    def format_text(self) -> str:
        lines = ["<!-- dhf-impact -->", "## DHF Impact Summary", ""]
        if self.auto_sections:
            lines.append("### Run `python scripts/generate_dhf.py` in COCA-prj-DHF")
            for s in self.auto_sections:
                lines.append(f"- `{s.dhf_file}` — {s.reason}")
            lines.append("")
        if self.manual_sections:
            lines.append("### Manual review required before merging")
            for s in self.manual_sections:
                lines.append(f"- `{s.dhf_file}` — {s.reason}")
            lines.append("")
        if not self.auto_sections and not self.manual_sections:
            lines.append("No DHF sections affected by these changes.")
            lines.append("")
        return "\n".join(lines)


# (pattern, dhf_file, label_or_reason)
# Pattern semantics: "**" = any file; "src/**" = any file under src/;
# otherwise fnmatch against the bare filename.
_AUTO_RULES: list[tuple[str, str, str]] = [
    ("docs/user_needs.yaml",        "02_requirements/system_requirements.md",       "requirements files changed"),
    ("docs/requirements.yaml",      "02_requirements/system_requirements.md",       "requirements files changed"),
    ("docs/design.yaml",            "02_requirements/system_requirements.md",       "requirements files changed"),
    ("docs/risk_controls.yaml",     "02_requirements/system_requirements.md",       "requirements files changed"),
    ("docs/user_needs.yaml",        "02_requirements/traceability_index.md",        "requirements or tests changed"),
    ("docs/requirements.yaml",      "02_requirements/traceability_index.md",        "requirements or tests changed"),
    ("docs/design.yaml",            "02_requirements/traceability_index.md",        "requirements or tests changed"),
    ("docs/risk_controls.yaml",     "02_requirements/traceability_index.md",        "requirements or tests changed"),
    ("tests/**",                    "02_requirements/traceability_index.md",        "requirements or tests changed"),
    ("docs/risk_controls.yaml",     "04_risk_management/risk_control_measures.md",  "risk_controls.yaml changed"),
    ("docs/hazard_analysis.yaml",   "04_risk_management/hazard_analysis.md",        "hazard_analysis.yaml changed"),
    ("docs/soup.yaml",              "05_soup/soup_register.md",                     "soup.yaml changed"),
    ("artifacts/evidence_runs/**",  "06_verification/evidence_index.md",            "evidence artifacts changed"),
    ("pyproject.toml",              "07_configuration_management/baseline_register.md", "version or deps changed"),
    ("**",                          "09_change_control/change_log.md",              "code changes detected"),
]

_MANUAL_RULES: list[tuple[str, str, str]] = [
    ("docs/user_needs.yaml",     "01_device_description/intended_use.md",          "intended use statement may need updating"),
    ("docs/risk_controls.yaml",  "04_risk_management/risk_control_measures.md",    "review implementation status column"),
    ("docs/risk_controls.yaml",  "04_risk_management/residual_risk_evaluation.md", "re-evaluate residual risk acceptability"),
    ("docs/hazard_analysis.yaml","04_risk_management/risk_management_plan.md",     "verify hazard analysis scope is current"),
    ("docs/soup.yaml",           "05_soup/soup_risk_analysis.md",                  "review SOUP failure modes for changed dependencies"),
    ("src/**",                   "03_architecture/software_architecture.md",       "verify architecture diagrams reflect changes"),
    ("src/**",                   "10_software_development_plan/sdp.md",            "source changes may affect design descriptions"),
    ("tests/**",                 "06_verification/verification_plan.md",           "verify test strategy covers new behavior"),
    ("pyproject.toml",           "07_configuration_management/baseline_register.md", "update version entry in baseline register"),
]


def _matches(pattern: str, file_path: str) -> bool:
    if pattern == "**":
        return True
    if pattern.endswith("/**"):
        prefix = pattern[:-3]
        return file_path == prefix or file_path.startswith(prefix + "/")
    return fnmatch.fnmatch(file_path, pattern)


class DHFImpactAnalyzer:
    """Classify DHF sections affected by a set of changed project file paths."""

    def analyze(self, changed_files: list[str]) -> ImpactReport:
        if not changed_files:
            return ImpactReport()

        # Collect triggered sections; deduplicate by dhf_file (first reason wins)
        auto: dict[str, ImpactSection] = {}
        manual: dict[str, ImpactSection] = {}

        for file_path in changed_files:
            for pattern, dhf_file, label in _AUTO_RULES:
                if dhf_file not in auto and _matches(pattern, file_path):
                    auto[dhf_file] = ImpactSection(dhf_file=dhf_file, reason=label, label=label)

            for pattern, dhf_file, reason in _MANUAL_RULES:
                if dhf_file not in manual and _matches(pattern, file_path):
                    manual[dhf_file] = ImpactSection(dhf_file=dhf_file, reason=reason, label=dhf_file)

        return ImpactReport(
            auto_sections=list(auto.values()),
            manual_sections=list(manual.values()),
        )


if __name__ == "__main__":
    import argparse
    import json as _json
    import sys

    parser = argparse.ArgumentParser(description="Analyze DHF impact of changed files.")
    parser.add_argument("--changed", nargs="*", default=[], metavar="FILE")
    parser.add_argument("--json", action="store_true", help="Output JSON instead of text")
    args = parser.parse_args()

    report = DHFImpactAnalyzer().analyze(args.changed)

    if args.json:
        print(_json.dumps({
            "auto_sections": [{"dhf_file": s.dhf_file, "reason": s.reason} for s in report.auto_sections],
            "manual_sections": [{"dhf_file": s.dhf_file, "reason": s.reason} for s in report.manual_sections],
        }))
    else:
        print(report.format_text())

    sys.exit(0)
