name: Auto-merge

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - dev

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  pull-requests: write
  contents: write

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --merge "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ github.token }}
